### ISSUE TITLE
crashing on windows 10

### ISSUE THREAD

**Issue by stevedipaola** [tomboy-notes/tomboy#37]
On windows 10 after following install instructions - Tomboy opens, goes to taskbar and closes. So I did a cmd  debug here - can anyone help me with what the issues is:

  C:\Users\root533>"C:\Program Files (x86)\Tomboy\Tomboy.exe" --debug

C:\Users\root533>[DEBUG 22:40:24.028] NoteManager created with note path "C:\Users\root533\AppData\Roaming\Tomboy\notes".
[DEBUG 22:40:24.066] EnableDisable Called: enabling... True
[DEBUG 22:40:24.068] Binding key '<Alt>F12' for '/apps/tomboy/global_keybindings/show_note_menu'
[WARN 22:40:24.073] Preference key '/apps/tomboy/global_keybindings/open_start_here' does not exist, using default.
[DEBUG 22:40:24.073] Binding key '<Alt>F11' for '/apps/tomboy/global_keybindings/open_start_here'
[WARN 22:40:24.073] Preference key '/apps/tomboy/global_keybindings/open_search' does not exist, using default.
[DEBUG 22:40:24.088] Unable to load icon 'tomboy-panel'.
[INFO 22:40:24.549] Initializing Mono.Addins
[DEBUG 22:40:24.586] AddinManager.OnAddinLoaded: Tomboy.Tomboy
[DEBUG 22:40:24.589]           Name: Tomboy.Tomboy,0.10
[DEBUG 22:40:24.589]    Description:
[DEBUG 22:40:24.589]      Namespace: Tomboy
[DEBUG 22:40:24.589]        Enabled: True
[DEBUG 22:40:24.589]           File: C:\Program Files (x86)\Tomboy\Tomboy.exe
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at Mono.Addins.AddinSessionService.CheckHostAssembly(Assembly asm)
   at Mono.Addins.AddinSessionService.ActivateRoots()
   at Mono.Addins.AddinSessionService.Initialize()
   at Mono.Addins.AddinManager.Initialize(String configDir)
   at Tomboy.AddinManager.InitializeMonoAddins(String old_conf_dir) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\AddinManager.cs:line 93
   at Tomboy.AddinManager..ctor(String tomboy_conf_dir, String old_tomboy_conf_dir) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\AddinManager.cs:line 45
   at Tomboy.NoteManager.Initialize() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\NoteManager.cs:line 138
   at Tomboy.Tomboy.<>c__DisplayClass11_0.<Main>b__0() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 101
   at GLib.Timeout.TimeoutProxy.Handler(IntPtr data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.Timeout.TimeoutProxy.Handler(IntPtr data)
   at Gtk.Application.gtk_main()
   at Tomboy.WindowsApplication.StartMainLoop() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\WindowsApplication.cs:line 87
   at Tomboy.Tomboy.StartTrayIcon() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 200
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 158

**Comment by alex-ter** [comment]
This is the same as issue #34 - you are probably using that newer version of the GTK#. Please use 2.12.38 instead, see download links in #34 and feel free to continue there if that doesn't work for whatever reason (though I've tested that, just not on WIndows 10).
