### ISSUE TITLE
Tomboy error on Win 8.1 Enterprise

### ISSUE THREAD

**Issue by mberbaum** [tomboy-notes/tomboy#60]
Greetings,
    I installed Tomboy but it's window will not come up:

Windows 8.1 Enterprise edition on Lenovo Yoga 11 laptop (4GB RAM, 128GB SSD)

Installed according to instructions at wiki.gnome.org/Apps/Tomboy/Installing/Windows
   gtk2-runtime-2.24.10-2012-10-10-ash.exe
   gtk-sharp-2.12.44.msi
   --- rebooted without being asked
   tomboy-1.15.9.msi
   -- no errors along the way, accepted defaults
   -- icon appears on desktop

PATH contains ..;C:\Program Files (x86)\GTK2-Runtime\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;

Problem: Clicking the desktop icon brings up User Account Control that asks whether I 
wish to run an Unknown program.  I Click 'Yes' but then nothing comes up on the screen.
Same result when Tomboy is invoked from the command line as shown below.  (Note: from 
the command line the debug info is shown whether or not I use the --debug switch.)

C:\Users\mberbaum\> "C:\Program Files (x86)\Tomboy\tomboy.exe" --debug

Unhandled Exception:  System.MissingMethodException: Method not found: 
'!!0[] System.Array.Empty()'
   at Gtk.UIManager..ctor()
   at Tomboy.ActionManager..ctor() 
         in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\ActionManager.cs:line 44
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args)
         in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 1070
   at Tomboy.Tomboy.Main(String[] args) 
         in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82

I'll appreciate any assistance!  --Mike Berbaum (mberbaum at uic dot edu)

**Comment by alex-ter** [comment]
That's very early in the init sequence. I'd need to look into the code for more meaningful comment, but just to understand it better - your account on that computer is I guess not in Administrators group, right? Typically it shouldn't be popping the UAC prompt up.

**Comment by mberbaum** [comment]
Alex,

    Thanks for getting back.

    I can run the command line as an administrator.  When I do, I do not get the User Account Control box popping up, but then I do get exactly the error message -- identical.

Best, --Mike

________________________________

**Comment by alex-ter** [comment]
After some additional checks I don't see any reason it should be failing because of the Tomboy itself, however I've found a plausible [.NET version-related issue](https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl).

Could you please check what .NET version you have installed and see if updating to 4.6 fixes the problem?

**Comment by mberbaum** [comment]
Alex,

    Almost fixed.  .NET 4.6.2 is now installed and clicking on the desktop icon brings up the screen box headed 'Search All Notes'.  However, the screen box is filled with little rectangles where the characters of the text should be.  What's up?

    I rebooted after installing .NET.  Both GTK2 and GTK# appeared in the PATH after running the Tomboy installer.  The installer also set an environment variable:

GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\

Is that still needed after installation?

    It turns out that the error message I described in my first post is also what one gets if .NET is not installed at all.

Thanks for your help!  --Mike


________________________________

**Comment by alex-ter** [comment]
Ok, good progress :-) Could uou please show me a screenshot with those rectangles? I've never seen anything like this before, so I'll need to investigate, but first - understand better. Your Windows is set to some English locale (language), isn't it?

That variable the installer creates is I believe necessary, yes.

**Comment by mberbaum** [comment]
Alex,

    I've attached screen shots of the Tomboy window in .jpg and .png .  Thanks for your help!  --Mike

________________________________

**Comment by alex-ter** [comment]
Hmm, I'm sorry, but I don't see any attachments - neither in the orignal issue description, nor in your last comment. Could you please double-check they've really got attached/uploaded?

**Comment by mberbaum** [comment]
Alex,

    Hmm, at my end it shows 4 attachments, two jpg and two png. I'll check and resend this afternoon (gotta go lecture just now).

--Mike

________________________________

**Comment by mberbaum** [comment]
Alex,

    Here's a zip file with the screen shots inside.  Perhaps your email client is protecting you from 'raw' attachments that could contain viruses?

--Mike

________________________________

**Comment by ajhepple** [comment]
Hi Mike. I think GitHub ignores all attachments when using email to respond directly to issues. Your email isn't sent directly to Alex. Instead, GitHub extract only the message content and create a corresponding issue comment. Alex (and any others who may be watching the issue/project) are subsequently notified by GitHub email that a new issue comment has been made. To attach files to issue comments you must use the GitHub web interface.
Hope this helps.

**Comment by mberbaum** [comment]
Thanks for the guidance, Anthony! 
Preview shows that the screen shots are visible. 
I think this could have something to do with font selection, but that pure guess.
Thanks again for the help.  Best, --Mike


![tomboy-screen-2](https://user-images.githubusercontent.com/1795101/29287758-8e963532-8104-11e7-874b-c6a5baed8f14.png)
![tomboy-screen-2](https://user-images.githubusercontent.com/1795101/29287759-8e963226-8104-11e7-9c7c-5c3c63522a6f.jpg)
![tomboy-screen-1](https://user-images.githubusercontent.com/1795101/29287761-8e9835b2-8104-11e7-9672-392de69046bc.png)
![tomboy-screen-1](https://user-images.githubusercontent.com/1795101/29287760-8e97075a-8104-11e7-84db-bdf6b5e4a247.jpg)

**Comment by alex-ter** [comment]
Thanks. You were attaching the files to the email when replying to the GitHub's notifications, right? Looks like that way they don't make it into the issue record.

But the direct post worked, it apparently looks to me like something OS-level again, as Tomboy does nothing fancy with the interface font (it's actually not configured and just GTK+ defaults are used, which is some commonplace font).

What's your setting under Control Panel\All Control Panel Items\Language?
Could you please try unchecking "Hide fonts based on language settings" checkbox under Control Panel\All Control Panel Items\Fonts\Font settings, to see if it changes anything?

Finally, you've closed the issue - I guess by accident, as you haven't mentoned that you've found a solution?

**Comment by mberbaum** [comment]
Alex,

    Will check settings as you suggest.  Do you happen to know Tomboy's default font ... perhaps it's not on my maschine?

    I did not intend to close the item -- oops, sorry!  Thanks for reopening it, as I'm not quite there yet.

Back to you fairly soon.

--Mike

________________________________

**Comment by alex-ter** [comment]
Finding out what the default font is turns out to be not that easy as it should be... Tomboy itself uses a GTK+ name of "Serif", which AFAIU is translated by the Pango library by means of Fontconfig library into specific font with the "closest match" of all parameters. And to check it one theoretically could use `fc-match` utility from fontconfig, but there's no read-made build for Windows.

My guess is that it should translate into MS Sans Serif or something similar, but then again - this one should be there by default. Worth checking though.

**Comment by mberbaum** [comment]
Alex,

    First, I checked the Language set in the Control Panel:  it is 'English (United States)'.


    Second, I tried unchecking "Hide fonts based on language setting".  No change (even restarted just to be sure).


    In my C:\Program Files (x86)\GTK2-Runtime\ I have 'gtk2-prefs.exe'  -- I tried running that and it too came up with little boxes where characters should have been (as in the screenshots).


    In C:\Program Files (x86)\GTK2-Runtime\etc\fonts\ I looked at 'fonts.conf' file.  It seems to convert 'sans' and 'sans serif' (with space) into 'sans-serif' (with hyphen). But I could not make out that it actually named a proper windows font or the name of a windows font file (such as reside in C:\Windows\Fonts\). The file 'fonts.conf' also seems to set environment variables for paths to fonts, WINDOWSFONTDIR or ~/.fonts .  But I'm guessing it never finds what it's looking for.


    This link seems relevant but not actually helpful:

https://superuser.com/questions/503911/how-to-change-tomboys-monospaced-font-on-windows


<https://superuser.com/questions/503911/how-to-change-tomboys-monospaced-font-on-windows>

    I also found alternate instructions for installation.  The one thing that it does that's useful is that it tells Windows users explicitly to install .NET (which the Gnome instructions do not).

http://www.pctips4u.com/2014/06/how-to-install-tomboy-notes-in-windows.html


    Here's a link about setting custom fonts in Tomboy (4th item down).  It seems to be referring to a 'Preferences' tab inside Tomboy itself.  At least on my Win 8.1 Enterprise I can right click the Tomboy icon and it will offer a 'Preferences' tab, but that has nothing in it anywhere about setting a font.

https://help.gnome.org/users/tomboy/stable/edit-prefs.html.en <https://help.gnome.org/users/tomboy/stable/edit-prefs.html.en> <https://help.gnome.org/users/tomboy/stable/edit-prefs.html.en>

It might be an idea to compile without disabling the option to use a font different than the desktop display.


    I feel like I'm missing something simple ... others must be getting Tomboy to work with Windows, or you would have heard more complaints!


    Anyway, I remain very grateful for the help I've already received, and still hope for a fix.  Tomboy seems like just the tool for my needs.


Best regards, --mike




________________________________

**Comment by alex-ter** [comment]
Apologies for a delay, this time it was my turn to attend to "real life" stuff :)

Yes, this is definitely not a commonplace issue, in fact I haven't ever seen anything like this and I've been watching the project for a number of years, even when not actively participating. So we'll get to the bottom of this, be sure :)

So you have English as the Language, but do you have "MS Sans Serif" and/or "Microsoft  Sans Serif" fonts? You can check by visiting Control Panel->Fonts and then searching for "serif".

As for the Tomboy setting you've found - it's irrelevant as it's about the note contents font, not the interface one. The .NET installation step is also optional these days - suitable version of .NET (4.5.x) is included with any recent version of Windows (wasn't the case some time ago, when Tomboy was already around, that's probably where that instrtuction step stems from). The specific issue you've faced originally, with having to install .NET version 4.6.x is actually a bug/peculiarity in .NET's assembly resolution, which I'll have to workaround/account for in Windows build.

**Comment by alex-ter** [comment]
Oh and BTW, this is actually very strange:

>  In my C:\Program Files (x86)\GTK2-Runtime\ I have 'gtk2-prefs.exe'

The recommended GTK+ build doesn't contain such a binary. Are you sure you've installed namely from `gtk2-runtime-2.24.10-2012-10-10-ash.exe`, which you can get e.g. [here](http://downloads.sourceforge.net/gtk-win/gtk2-runtime-2.24.10-2012-10-10-ash.exe?download)? Could you please show a screenshot of the `bin` directory under `GTK-Runtime`?

**Comment by mberbaum** [comment]
Alex,

    "Real life" happens!

    From the Control Panel > Fonts I found "Microsoft Sans Serif Regular".  In the C:\Windows\Fonts subdirectory I found a file 'micross.ttf' which opens and reports "Microsoft Sans Serif" version 6.03, OpenType Layout, Digitally Signed, TrueType Outlines.  There are many other serif fonts in that subdirectory as well.  I wonder what exactly Tomboy (or GTK+) looks for ... a specific font name or a font family or what?

Regards, --Mike

________________________________

**Comment by alex-ter** [comment]
The specific font is unfortunately unknown as it's determined at runtime by fontconfig library, which doesn't (in the GTK+ package we have) have the fc-match utility which shows just that - which actal font it picks for that "sans-serif" name it requests.

In my setup I also have "MS Sans Serif" font, do you have such one?

And what about that gtk2-prefs.exe, if you have something like that it most probably means you have a different GTK+ package than I do (recommended one).

**Comment by mberbaum** [comment]
Alex,

    There are apparently two different Microsoft Sans Serif fonts (at least).  The original that came with Windows in the early days was "MS Sans Serif" and was in files sserife.fon and sseriff.fon -- fon extension tells us bitmap font.  Then came the True Type version, "Microsoft Sans Serif" in file micross.ttf.  I have both in the subdirectory C:\Windows\Fonts.

Best, --Mike

________________________________

**Comment by alex-ter** [comment]
>And what about that gtk2-prefs.exe, if you have something like that it most probably means you have a different GTK+ package than I do (recommended one).

? :)

**Comment by mberbaum** [comment]
Alex,


    The file I was referring to was the "GTK+ Preference Tool" (which is in a file named 'gtk2-prefs.exe', dated 2008-01-20, size 293,371b). I found it here:


        https://gtk-win.sourceforge.io/home/index.php

At the bottom of the web page it says the software is no longer maintained.  But when you run it, it also shows little boxes instead of characters, just as Tomboy does.  I don't think this is likely to be the source of the problem, but what do I know?


Sorry for the delay getting you this information.  --Mike


GTK+ for Windows Runtime Environment - Browse /GTK+ Themes ...<https://sourceforge.net/projects/gtk-win/files/GTK%2B%20Themes%20Package/2009-09-07/>
sourceforge.net
The files required to run GTK+ applications on Windows



________________________________

**Comment by alex-ter** [comment]
I see. Well, I'm sorry to say that, but I'm out of ideas at this point. This is definitely not something anyone has reported before, so there must be something unique in your system, which causes this, but I can't really image what, sorry. Maybe someone passing by would have other things to try...

**Comment by mberbaum** [comment]
Alex,

    I think I'll just try a reinstall -- that's one thing I didn't do after I upgraded 4.6.2.  I could get lucky!

    Thanks for all your help!  --Mike

________________________________
