### ISSUE TITLE
Tomboy 1.15.7 crashes on launch (Windows 7)

### ISSUE THREAD

**Issue by TinaRussell** [tomboy-notes/tomboy#71]
I’m using Windows 7, 32-bit. I installed Tomboy 1.15.7 via Chocolatey, which I use because I’m used to Linux package managers, and the thought of having to keep each program on my computer up to date separately terrifies me.
I’ve used Tomboy on this machine just fine until recently. Now, Tomboy crashes immediately after I start it. When run from the shell, Tomboy produces this result:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'glibsharpglue-2': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)
   at GLib.ObjectManager.gtksharp_get_type_id(IntPtr raw)
   at GLib.ObjectManager.GetTypeOrParent(IntPtr obj)
   at GLib.ObjectManager.CreateObject(IntPtr raw)
   at GLib.Object.GetObject(IntPtr o, Boolean owned_ref)
   at Gtk.IconTheme.get_Default()
   at Tomboy.GuiUtils.GetIcon(Assembly asm, String resource_name, Int32 size) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 145
   at Tomboy.ActionManager..ctor() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\ActionManager.cs:line 52
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\My Docs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 1075
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82
```
It seems that Tomboy (or a different Chocolatey package) installed the package for the .NET Framework 4.0, which of course the Tomboy website says is out of date. So, I installed the .NET Framework 4.7 package to see if it would make a difference, then rebooted…  no luck, Tomboy still produces the same with the same traceback.

![image](https://user-images.githubusercontent.com/31976617/30463599-885ba3a6-9981-11e7-875e-10936c5ff507.png)

Any help would be appreciated!

**Comment by ajhepple** [comment]
Did you see issue #67? It contains some advice and a fix for a very similar, if not identical, problem to yours.

**Comment by shoresh** [comment]
The fix from issue #67 did not work for me.  It just generated new errors:
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at Mono.Addins.AddinSessionService.CheckHostAssembly(Assembly asm)
   at Mono.Addins.AddinSessionService.ActivateRoots()
   at Mono.Addins.AddinSessionService.Initialize()
   at Mono.Addins.AddinManager.Initialize(String configDir)
   at Tomboy.AddinManager.InitializeMonoAddins(String old_conf_dir) in C:\Projects\tomboy-gnome\Tomboy\AddinManager.cs:line 93
   at Tomboy.AddinManager..ctor(String tomboy_conf_dir, String old_tomboy_conf_dir) in C:\Projects\tomboy-gnome\Tomboy\AddinManager.cs:line 45
   at Tomboy.NoteManager.Initialize() in C:\Projects\tomboy-gnome\Tomboy\NoteManager.cs:line 138
   at Tomboy.Tomboy.<>c__DisplayClass4.<Main>b__0() in C:\Projects\tomboy-gnome\Tomboy\Tomboy.cs:line 101
   at GLib.Timeout.TimeoutProxy.Invoke(IntPtr data)
   at GLib.SourceProxy.HandlerInternal(IntPtr data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SourceProxy.HandlerInternal(IntPtr data)
   at Gtk.Application.gtk_main()
   at Tomboy.WindowsApplication.StartMainLoop() in C:\Projects\tomboy-gnome\Tomboy\WindowsApplication.cs:line 87
   at Tomboy.Tomboy.StartTrayIcon() in C:\Projects\tomboy-gnome\Tomboy\Tomboy.cs:line 200
   at Tomboy.Tomboy.Main(String[] args) in C:\Projects\tomboy-gnome\Tomboy\Tomboy.cs:line 158

**Comment by fpp-gh** [comment]
Hi,
Same thing here, fresh install on W7SP1 (no previous use of Tomboy except under Linux), as per the Wiki.

Debug output is (pardon my French :-):
C:\Program Files (x86)\Tomboy>Tomboy.exe --debug
Exception non gérée : System.DllNotFoundException: Impossible de charger la DLL 'glibsharpglue-2': La procédure spécifiée est introuvable. (Exception de HRESULT : 0x8007007F)
   à GLib.ObjectManager.gtksharp_get_type_id(IntPtr raw)
   à GLib.ObjectManager.GetTypeOrParent(IntPtr obj)
   à GLib.ObjectManager.CreateObject(IntPtr raw)
   à GLib.Object.GetObject(IntPtr o, Boolean owned_ref)
   à Gtk.IconTheme.get_Default()
   à Tomboy.GuiUtils.GetIcon(Assembly asm, String resource_name, Int32 size) dans C:\MyDoc\dev\tomboy\tomboy-github\Tomboy\Utils.cs:ligne 145
   à Tomboy.ActionManager..ctor() dans C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\ActionManager.cs:ligne 52
   à Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) dans C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:ligne 1070
   à Tomboy.Tomboy.Main(String[] args) dans C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:ligne 82

There is only one glibsharpglue-2.dll on the system (from GtkSharp 2.12 fresh install).

**Comment by fpp-gh** [comment]
Update: on a hunch I tried setting ```tomboy_path_prefix``` as recommended in issue #67.
Although I did accept all installer defaults, and have GTK2 and GtkSharp in the system path, adding this seemed to be enough in my case...

**Comment by shoresh** [comment]
That did not solve it for me.

**Comment by lintunen** [comment]
I can confirm this issue is still happening on a clean install of Tomboy (1.15.9) (and associated libraries) on Windows 10 (version 1709). I fixed the problem as per the above suggestion in issue #67 by copying the older version of _glibsharpglue-2.dll_ from the Unity thread.

**Comment by guiNovais** [comment]
I found a solution at #97
