### ISSUE TITLE
Failure to install Tomboy 1.15.x on Windows 10

### ISSUE THREAD

**Issue by pablomguevara** [tomboy-notes/tomboy#88]
Hi there, I tried multiple versions (1.15.9 and 1.15.5 being the latest) , all fail.
I reinstalled multiple times. I followed [instructions ](https://wiki.gnome.org/Apps/Tomboy/Installing/Windows)to the letter but still windows complains that is not able to find the dll. The path is right and the referenced bin folders that the right dlls.

`C:\Users\user>"c:\Program Files (x86)\Tomboy\Tomboy.exe" --debug

C:\Users\user>
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libglib-2.0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at GLib.Marshaller.g_utf16_to_utf8(Char* native_str, IntPtr len, IntPtr items_read, IntPtr items_written, IntPtr& error)
   at GLib.Marshaller.StringToPtrGStrdup(String str)
   at GLib.Global.set_ProgramName(String value)
   at Gtk.Application.SetPrgname()
   at Gtk.Application.Init()
   at Tomboy.WindowsApplication.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\WindowsApplication.cs:line 64
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 1068
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82

C:\Users\user>path
PATH=C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Android;C:\Windows\System32;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\GTK2-Runtime\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;

C:\Users\user>cd C:\Program Files (x86)\GtkSharp\2.12\bin

C:\Program Files (x86)\GtkSharp\2.12\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 885C-2E96

 Directory of C:\Program Files (x86)\GtkSharp\2.12\bin

01/17/2018  09:54 AM    <DIR>          .
01/17/2018  09:54 AM    <DIR>          ..
05/31/2017  12:39 PM            24,064 atksharpglue-2.dll
11/27/2012  04:39 PM            42,548 gdk-pixbuf-query-loaders.exe
05/31/2017  12:39 PM            31,232 gdksharpglue-2.dll
05/31/2017  12:41 PM            15,360 gladesharpglue-2.dll
05/31/2017  12:39 PM            22,016 glibsharpglue-2.dll
11/27/2012  02:56 PM            40,290 gspawn-win32-helper-console.exe
11/27/2012  02:56 PM            40,290 gspawn-win32-helper.exe
12/04/2012  01:10 PM            43,038 gtk-query-immodules-2.0.exe
05/31/2017  12:40 PM           129,024 gtksharpglue-2.dll
11/27/2012  09:27 AM        18,312,397 icudata48.dll
11/27/2012  09:27 AM         2,009,488 icui18n48.dll
11/27/2012  09:27 AM            69,965 icuio48.dll
11/27/2012  09:27 AM           259,267 icule48.dll
11/27/2012  09:27 AM            69,034 iculx48.dll
11/27/2012  09:27 AM           163,851 icutu48.dll
11/27/2012  09:27 AM         1,297,594 icuuc48.dll
07/31/2014  03:07 PM           109,990 intl.dll
09/18/2016  05:03 AM           114,176 libatk-1.0-0.dll
09/18/2016  05:03 AM         1,180,160 libcairo-2.dll
11/27/2012  05:12 PM           225,931 libcroco-0.6-3.dll
11/27/2012  10:57 AM           175,196 libexpat-1.dll
11/13/2013  08:10 PM            52,640 libffi-6.dll
11/27/2012  10:38 AM           237,207 libfontconfig-1.dll
11/27/2012  10:26 AM           493,606 libfreetype-6.dll
09/18/2016  05:03 AM            28,160 libgailutil-2.0-0.dll
11/27/2012  09:55 AM           120,916 libgcc_s_sjlj-1.dll
09/18/2016  05:03 AM           579,584 libgdk-win32-2.0-0.dll
09/18/2016  05:03 AM           163,328 libgdk_pixbuf-2.0-0.dll
09/18/2016  05:03 AM         1,168,896 libgio-2.0-0.dll
01/14/2013  12:35 PM           135,569 libglade-2.0-0.dll
09/18/2016  05:03 AM         1,130,496 libglib-2.0-0.dll
09/18/2016  05:03 AM            13,824 libgmodule-2.0-0.dll
09/18/2016  05:03 AM           206,848 libgobject-2.0-0.dll
11/27/2012  05:37 PM           243,306 libgsf-1-114.dll
11/27/2012  05:37 PM            42,305 libgsf-win32-1-114.dll
09/18/2016  05:03 AM             8,192 libgthread-2.0-0.dll
09/18/2016  05:03 AM         3,512,320 libgtk-win32-2.0-0.dll
01/14/2013  11:08 AM           567,288 libharfbuzz-0.dll
07/31/2014  03:07 PM           109,990 libintl-8.dll
11/27/2012  12:52 PM           282,742 libjasper-1.dll
04/14/2017  09:31 AM         1,154,192 libjpeg-8.dll
11/27/2012  12:58 PM           158,594 liblzma-5.dll
09/18/2016  05:03 AM           252,928 libpango-1.0-0.dll
09/18/2016  05:03 AM           442,368 libpangocairo-1.0-0.dll
09/18/2016  05:03 AM           462,848 libpangoft2-1.0-0.dll
09/18/2016  05:03 AM            54,272 libpangowin32-1.0-0.dll
09/18/2016  05:03 AM           589,824 libpixman-1-0.dll
11/27/2012  10:23 AM           177,192 libpng15-15.dll
09/18/2016  05:03 AM           167,936 libpng16.dll
01/14/2013  12:39 PM           242,729 librsvg-2-2.dll
11/27/2012  09:56 AM           864,381 libstdc++-6.dll
11/27/2012  01:10 PM           448,770 libtiff-5.dll
11/27/2012  10:29 AM         1,161,549 libxml2-2.dll
01/20/2016  03:48 PM           393,416 MonoPosixHelper.dll
01/28/2013  08:27 AM            42,960 pango-querymodules.exe
05/31/2017  12:39 PM            19,968 pangosharpglue-2.dll
11/27/2012  09:10 AM           107,212 zlib1.dll
              57 File(s)     40,213,267 bytes
               2 Dir(s)  254,212,014,080 bytes free

C:\Program Files (x86)\GtkSharp\2.12\bin>cd C:\Program Files (x86)\GTK2-Runtime\bin

C:\Program Files (x86)\GTK2-Runtime\bin>dir
 Volume in drive C has no label.
 Volume Serial Number is 885C-2E96

 Directory of C:\Program Files (x86)\GTK2-Runtime\bin

01/17/2018  09:53 AM    <DIR>          .
01/17/2018  09:53 AM    <DIR>          ..
02/05/2010  11:55 AM            38,954 fc-cache.exe
02/05/2010  11:55 AM            29,379 fc-list.exe
12/27/2010  04:12 AM           538,324 freetype6.dll
11/21/2011  03:13 AM            33,941 gdk-pixbuf-query-loaders.exe
07/18/2011  11:42 PM            30,100 gspawn-win32-helper-console.exe
07/18/2011  11:42 PM            30,678 gspawn-win32-helper.exe
02/08/2012  11:35 AM            32,693 gtk-query-immodules-2.0.exe
02/08/2012  11:35 AM            58,401 gtk-update-icon-cache.exe
02/08/2012  11:34 AM               583 gtk-update-icon-cache.exe.manifest
09/11/2010  10:22 PM           152,489 intl.dll
07/18/2011  10:25 AM           163,476 libatk-1.0-0.dll
11/22/2011  12:48 AM         1,294,335 libcairo-2.dll
11/22/2011  12:49 AM            44,049 libcairo-gobject-2.dll
11/22/2011  12:50 AM           182,789 libcairo-script-interpreter-2.dll
01/31/2009  12:42 PM           143,096 libexpat-1.dll
02/05/2010  11:55 AM           279,059 libfontconfig-1.dll
02/08/2012  11:38 AM            60,599 libgailutil-18.dll
02/08/2012  11:25 AM           932,373 libgdk-win32-2.0-0.dll
11/21/2011  03:13 AM           285,194 libgdk_pixbuf-2.0-0.dll
07/19/2011  12:01 AM         1,222,182 libgio-2.0-0.dll
07/18/2011  11:42 PM         1,242,929 libglib-2.0-0.dll
07/18/2011  11:50 PM            36,986 libgmodule-2.0-0.dll
07/18/2011  11:53 PM           341,594 libgobject-2.0-0.dll
07/18/2011  11:50 PM            44,287 libgthread-2.0-0.dll
02/08/2012  11:35 AM         4,939,820 libgtk-win32-2.0-0.dll
11/17/2011  04:53 AM           333,729 libpango-1.0-0.dll
11/17/2011  04:53 AM           104,729 libpangocairo-1.0-0.dll
11/17/2011  04:53 AM           815,421 libpangoft2-1.0-0.dll
11/17/2011  04:53 AM           108,945 libpangowin32-1.0-0.dll
08/17/2010  06:38 AM           230,529 libpng14-14.dll
11/17/2011  04:53 AM            33,439 pango-querymodules.exe
08/20/2010  01:18 AM           100,352 zlib1.dll
              32 File(s)     13,885,454 bytes
               2 Dir(s)  254,426,587,136 bytes free

C:\Program Files (x86)\GTK2-Runtime\bin>
C:\Program Files (x86)\GTK2-Runtime\bin>
C:\Program Files (x86)\GTK2-Runtime\bin>`

**Comment by c0d3th1sn0w** [comment]
Hi,
I am facing (almost) the same issue with Tomboy installation on Win10. The error is for 'glibsharpglue-2' dll file, which is present in 'C:\Program Files (x86)\GtkSharp\2.12\bin' and same is set in PATH variable.

Have you been able to solve this issue?

Thanks

**Comment by pablomguevara** [comment]
No, I have not fixed It. I kind of gave up for the time being.

**Comment by jratcliffe** [comment]
Re: The glibsharpglue-2 error:

I had to create a System variable (System Properties->Advanced Tab->Environment Variables) called "TOMBOY_PATH_PREFIX" with the value "C:\Program Files (x86)\GtkSharp\2.12\bin" (no quotes).  You should double-check that the missing dll file is in that folder, of course.

**Comment by pablomguevara** [comment]
So with that variable it working?

**Comment by floriel** [comment]
@pablomguevara I had the same issue on Win 7 and the workaround from @jratcliffe worked for me.

**Comment by guiNovais** [comment]
I found a solution at #97

**Comment by GunArm** [comment]
Like @guiAlberto said, I read #97, uninstalled the gtksharp I had just installed (2.12.45) and installed the older gtksharp linked to on #97 (2.12.21).  After that tomboy works fine.  I didn't reinstall gtk2-runtime or tomboy to make it work, just downgraded gtksharp to 2.12.21

**Comment by siplo** [comment]
TOMBOY_PATH_PREFIX works for me. Thanks.
