### ISSUE TITLE
Windows update on Windows 10 Stopped Tomboy Notes Working.

### ISSUE THREAD

**Issue by vishalanil12** [tomboy-notes/tomboy#91]
Hello, I am using Windows 10 1709 and last night I ran windows updates. After that , Tomboy Notes stopped working. Cursor rotates but the application doesn't open up. Debug shows dll missing. I reinstalled gtk, gtksharp, mono, Tomboy Notes. Now debug shows below error :- 

C:\WINDOWS\system32>
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'glibsharpglue-2': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)
   at GLib.ObjectManager.gtksharp_get_type_id(IntPtr raw)
   at GLib.ObjectManager.GetTypeOrParent(IntPtr obj)
   at GLib.ObjectManager.CreateObject(IntPtr raw)
   at GLib.Object.GetObject(IntPtr o, Boolean owned_ref)
   at Gtk.IconTheme.get_Default()
   at Tomboy.GuiUtils.GetIcon(Assembly asm, String resource_name, Int32 size) in C:\Projects\tomboy-gnome\Tomboy\Utils.cs:line 145
   at Tomboy.ActionManager..ctor() in C:\Projects\tomboy-gnome\Tomboy\ActionManager.cs:line 52
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\Projects\tomboy-gnome\Tomboy\Utils.cs:line 990
   at Tomboy.Tomboy.Main(String[] args) in C:\Projects\tomboy-gnome\Tomboy\Tomboy.cs:line 82

Path Variable is showing the path of glibsharpglue. How can I resolve this. Please help.

Thanks & Regards,
Vishal

**Comment by emgee-909** [comment]
I have similar problem with loading dll. Except I get

`Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libgtk-win32-2.0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Gtk.Application.gtk_init(Int32& argc, IntPtr& argv)
   at Gtk.Application.Init()
   at Tomboy.WindowsApplication.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\WindowsApplication.cs:line 64
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 1068
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82`

And this is path command result

`PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\GTK2-Runtime\bin;C:\Users\blabla\AppData\Local\Microsoft\WindowsApps;`

**Comment by Yaroslav-Pryadunov** [comment]
In 2024, the problem is still relevant.

**Comment by decriptor** [comment]
I don't have much time, but maybe I can try and take a look at it this week.
