### ISSUE TITLE
Tomboy (still) not starts on Windows 7

### ISSUE THREAD

**Issue by sagypt** [tomboy-notes/tomboy#97]
```
C:\Users\User>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\User\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=VM
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOMEDRIVE=C:
HOMEPATH=\Users\User
LOCALAPPDATA=C:\Users\User\AppData\Local
LOGONSERVER=\\VM
NUMBER_OF_PROCESSORS=1
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3d04
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\User\AppData\Local\Temp
TMP=C:\Users\User\AppData\Local\Temp
TOMBOY_PATH_PREFIX=C:\Program Files (x86)\GtkSharp\2.12\bin
USERDOMAIN=VM
USERNAME=User
USERPROFILE=C:\Users\User
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
```

Control Panel > System and Security > System > Advanced System Settings > Advanced > Environment Variables > System Variables ... TOMBOY_PATH_PREFIX
```
C:\Users\User>echo %TOMBOY_PATH_PREFIX%
C:\Program Files (x86)\GtkSharp\2.12\bin
```
```
C:\Users\User>dir "C:\Program Files (x86)\GtkSharp\2.12\bin\libglib*"
 Volume in drive C is OS
 Volume Serial Number is A0B3-5303

 Directory of C:\Program Files (x86)\GtkSharp\2.12\bin

18/09/2016  05:03         1.130.496 libglib-2.0-0.dll
               1 File(s)      1.130.496 bytes
               0 Dir(s)  29.602.000.896 bytes free

```
```
C:\Users\User>"C:\Program Files (x86)\Tomboy\Tomboy.exe" --debug

C:\Users\User>
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libglib-2.0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x80
07007E)
   at GLib.Marshaller.g_utf16_to_utf8(Char* native_str, IntPtr len, IntPtr items_read, IntPtr items_written, IntPtr& error)
   at GLib.Marshaller.StringToPtrGStrdup(String str)
   at GLib.Global.set_ProgramName(String value)
   at Gtk.Application.SetPrgname()
   at Gtk.Application.Init()
   at Tomboy.WindowsApplication.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tom
boy\WindowsApplication.cs:line 64
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Uti
ls.cs:line 1068
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82

```

I also tried to reinstall Tomboy and libraries more times ...

**Comment by davidbannon** [comment]
sagypt, I doubt I can help but ..
Can you do a search for libglib-2.0-0.dll ?  You will have to turn off the "hide system files" option first. Its possible that file is not present or is in the wrong place or has a slightly different name. So, perhaps search for "libglib* ?
Sorry, I am not a Windows user, (only time I ever use it is to test tomboy-ng) so my exact wording will probably be wrong.
Maybe another windows user can tell us where they expect to find libglib ?
Davo

**Comment by sagypt** [comment]
Hi David,
thanks for your reply.

As written above, the DLL libglib-2.0-0.dll is only contained in folder C:\Program Files (x86)\GtkSharp\2.12\bin . This path is contained in system environment variables PATH and TOMBOY_PATH_PREFIX

**Comment by davidbannon** [comment]
Hmm, again, remember I don't do windows, I notice you appear to have a 64bit system -
"_PROCESSOR_ARCHITECTURE=AMD64_"
but are using 32bit GTK libraries ?
Are you sure thats the way it should be ? 
On the other hand, maybe you are running 32bit windows ?
"_ComSpec=C:\Windows\system32\cmd.exe_"
Ah, "_COMPUTERNAME=VM_" - are you running a 32bit version of windows in a VM on a 64bit machine ?
So, guessing still. You need a path set to to where that DLL is, maybe thats covered by -
"_TOMBOY_PATH_PREFIX=C:\Program Files (x86)\GtkSharp\2.12\bin_" ?? Maybe not ...

Perhaps, if feeling adventurous, from the command prompt, cd to the C:\Program Files (x86)\GtkSharp\2.12\bin directory and try and start Tomboy from there. Otherwise, we need to find out how to tell a windows app where to look for its DLLs. Anyone ?

Davo

**Comment by sagypt** [comment]
You don't do Windows ... I'm not good in English ... :-D

The system is a virtual machine with x64 architecture. The OS is Windows 7 SP1 - x64.

As indicated in installation instructions, I installed GTK# for .NET downloading the package from this URL http://www.mono-project.com/download/stable/ . Only the package gtk-sharp-2.12.45.msi is available.

(I guess that) The system environment variables PATH and TOMBOY_PATH_PREFIX are correctly setted
```
echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin
```
```
echo %TOMBOY_PATH_PREFIX%
C:\Program Files (x86)\GtkSharp\2.12\bin
```
Yes, I already tried to start Tomboy from the folder C:\Program Files (x86)\GtkSharp\2.12\bin but it doesn't starts

```
C:\Program Files (x86)\GtkSharp\2.12\bin>
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libglib-2.0-0.dll': The specified module could not be found. (Exception from HRESULT: 0x80
07007E)
   at GLib.Marshaller.g_utf16_to_utf8(Char* native_str, IntPtr len, IntPtr items_read, IntPtr items_written, IntPtr& error)
   at GLib.Marshaller.StringToPtrGStrdup(String str)
   at GLib.Global.set_ProgramName(String value)
   at Gtk.Application.SetPrgname()
   at Gtk.Application.Init()
   at Tomboy.WindowsApplication.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tom
boy\WindowsApplication.cs:line 64
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Uti
ls.cs:line 1068
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82

```

**Comment by davidbannon** [comment]
Sorry sagypt, it beats me. If your VM is 64bit, I would expect you to need a 64bit DLL. But you do seem to have a lot of 32bit paths. But, sorry, its beyond me !
The main reason I started tomboy-ng rather than putting my poor efforts into the existing Tomboy was the growing problem people were having solving the various dependencies on Windows and Mac.
Have you tried using tomboy-ng ? It has NO dependencies (although if you want to use the spell checker, you might need to get hunspell).
I'll be pushing out a new release (v0.15)of tomboy-ng in the next week or so.

**Comment by sagypt** [comment]
I fixed with the installation of library gtk-sharp-**2.12.21**.msi - URL: http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.21.msi
This version of library works both x64 and x86 architecture.

The environment variable TOMBOY_PATH_PREFIX isn't necessary.

**Comment by guiNovais** [comment]
Thanks @sagypt it also worked for me! And I'm using a Windows 10.0.17134

**Comment by mauri89** [comment]
Thanks @sagypt for finding this workaround!
I uninstalled my gtksharp 2.12.45, then I downloaded and run the gtksharp 2.12.21 msi installer linked in the post by sagypt from May 13th. This solved the issue for me.
I didn't need to reinstall my Tomboy installation.
In other words, I simply downgraded my gtksharp from 2.12.45 to 2.12.21 and the DLL in question was immediately recognized by tomboy, which now runs fine.
I report from a machine running Windows 7.

**Comment by bytersproblem** [comment]
Where to find the old version of GTK# today, when all the links are uavailable. I cannot find the 2.12.21 anywhere.

**Comment by bytersproblem** [comment]
Anyways, I downloaded it in the wayback machine on internetarchive.

**Comment by davidbannon** [comment]
Oh, wow, Nukedone, is it worth the effort ?  Have you considered tomboy-ng ?

If you have, and rejected it, would you mind telling me why ?

Davo

**Comment by bytersproblem** [comment]
I have tried. But I don’t like the options for syncing. And, moreover, all my notes are trapped in the Rainy Web Sync or Grauphel for Nextcloud, so I could not get my notes back with tomboy-ng.  Sent from Mail for Windows From: davidbannonSent: Saturday, October 9, 2021 10:46 AMTo: tomboy-notes/tomboyCc: nukedone; CommentSubject: Re: [tomboy-notes/tomboy] Tomboy (still) not starts on Windows 7 (#97) Oh, wow, Nukedone, is it worth the effort ? Have you considered tomboy-ng ?If you have, and rejected it, would you mind telling me why ?Davo—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
